import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Input, useColorMode } from '@chakra-ui/react'
import { InputGroup } from '@chakra-ui/react'
import { Button } from '@chakra-ui/react'
export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()
  return (
    <div className={styles.container}>
      <Head>
        <title>WSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SemWeb <a href="">Wibu Search Engine</a>
        </h1>
        <p className={styles.description}>
          WSE is a semantic web search engine using myAnimeList as its data. Hence its name WSE (Weaboo Search engine)
        </p>
        <Input w="80%" placeholder='Search' />
      </main>
    </div>
  )
}
